export const env = {
  databaseUrl: process.env.DATABASE_URL || '',
  skipDbCheck: (process.env.SKIP_DB_CHECK || 'false').toLowerCase() === 'true',
  redisUrl: process.env.REDIS_URL || '',
  sqsQueueUrl: process.env.SQS_QUEUE_URL || '',
  externalApiUrl: process.env.EXTERNAL_API_URL || '',
  externalApiKey: process.env.EXTERNAL_API_KEY || '',
  sentinelHubClientId: process.env.SENTINEL_HUB_CLIENT_ID || '',
  sentinelHubClientSecret: process.env.SENTINEL_HUB_CLIENT_SECRET || '',
  sentinelHubInstanceId: process.env.SENTINEL_HUB_INSTANCE_ID || '',
  sentinelHubLayerId: process.env.SENTINEL_HUB_LAYER_ID || 'S2L2A',
  sentinelHubMaxCloud: Number(process.env.SENTINEL_HUB_MAX_CLOUD ?? 20),
  sentinelHubSize: Number(process.env.SENTINEL_HUB_SIZE ?? 512),
  sentinelHubResolution: Number(process.env.SENTINEL_HUB_RESOLUTION ?? 10),
  sentinelHubEvalScript: process.env.SENTINEL_HUB_EVAL_SCRIPT || 'return [B04, B03, B02];',
  sentinelHubFormat: process.env.SENTINEL_HUB_FORMAT || 'image/png',
  sentinelHubTimeRangeDays: Number(process.env.SENTINEL_HUB_TIME_RANGE_DAYS ?? 30),
  sentinelHubAuthUrl: process.env.SENTINEL_HUB_AUTH_URL || 'https://services.sentinel-hub.com/oauth/token',
  sentinelHubProcessUrl: process.env.SENTINEL_HUB_PROCESS_URL || 'https://services.sentinel-hub.com/api/v1/process',
};